### ISSUE TITLE
Relicense to GPLv2+

### ISSUE THREAD

**Issue by sanchaez** [Amebis/libatl#2]
Hi, i'm a student working on a project in ReactOS. We want to use this library, however, ReactOS is GPLv2+ thus we can't use GPLv3 libraries without relicensing the whole codebase. Since it seems small I decided to ask you to relicense it as GPLv2+ so it could be used in the project :)

**Comment by rozmansi** [comment]
Personally, I have no objections. However, I am waiting for our legal team to reply. Will keep you posted.

**Comment by rozmansi** [comment]
By GPLv2+ you are referring to _"GNU GPLv2 or any later version as published by the Free Software Foundation"_, right?

**Comment by sanchaez** [comment]
@rozmansi  yes, exactly

**Comment by sanchaez** [comment]
Thank you!
